CREATE (AF:Item{nome: "Air Force 1", sku: 11})
CREATE (FR:Item{nome: "Free Run", sku: 22})
CREATE (AM98:Item{nome: "AirMax 98", sku: 33})
CREATE (NikeHoodie:Item {nome: "Felpa con Cappuccio", sku: 44 })
CREATE (AdidasHoodie:Item {nome: "Felpa senza Cappuccio", sku: 55})